# Generated by Django 4.2.2 on 2023-06-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(verbose_name='조회수'),
        ),
    ]
